### ISSUE TITLE
ClassNotFoundException ...worldedit.math.BlockVector3

### ISSUE THREAD

**Issue by Blitheness** [oliverdunk/JukeboxAPI#37]
Hey there,

Do you know what could possibly be causing these exceptions during startup on my server?

This appears a lot: "java.lang.ClassNotFoundException: com.sk89q.worldedit.math.BlockVector3".

Running:
- Paper build 486.
- Citizens version 2.0.24-SNAPSHOT (build 1605)
- FastAsyncWorldEdit version 1.0 (FAWE-1.13, build 125, 24 Dec 2018)
- WorldGuard version 7.0.0-SNAPSHOT;0dc5781
- MCJukebox version 2.6.0

My problems started when I added the MCJukebox update for 1.13.2. I previously had MCJukebox disabled.

Thank you

------

> [09:21:06 INFO]: [MCJukebox] Key accepted and connection to MCJukebox established.
> [09:21:07 INFO]: [MCJukebox] Predicted time offset: 19042ms.
> [09:21:07 INFO]: [MCJukebox] This will be silently updated every 30 seconds.

Then,

> [09:21:07 ERROR]: Could not pass event PlayerTeleportEvent to MCJukebox v2.6.0
> java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
>         at net.mcjukebox.shared.wg7.RegionProvider.getApplicableRegions(RegionProvider.java:30) ~[?:?]
>         at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onMove(RegionListener.java:59) ~[?:?]
>         at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onTeleport(RegionListener.java:42) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor382.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-486]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:723) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:334) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:233) ~[?:?]
>         at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:143) ~[?:?]
>         at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
>         at net.citizensnpcs.Citizens$2.run(Citizens.java:306) ~[?:?]
>         at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-486]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
> Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.BlockVector3
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-486]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
>         ... 21 more

and

> [09:21:11 ERROR]: Could not pass event PlayerTeleportEvent to MCJukebox v2.6.0
> java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
>         at net.mcjukebox.shared.wg7.RegionProvider.getApplicableRegions(RegionProvider.java:30) ~[?:?]
>         at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onMove(RegionListener.java:59) ~[?:?]
>         at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onTeleport(RegionListener.java:42) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor382.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-486]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:723) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:334) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:233) ~[?:?]
>         at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:190) ~[?:?]
>         at net.citizensnpcs.EventListen.spawn(EventListen.java:608) ~[?:?]
>         at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:578) ~[?:?]
>         at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:144) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor167.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-486]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.Chunk.addEntities(Chunk.java:991) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.postChunk(PaperAsyncChunkProvider.java:533) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.postChunkToMain(PaperAsyncChunkProvider.java:485) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.loadFinished(PaperAsyncChunkProvider.java:434) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.run(PaperAsyncChunkProvider.java:576) ~[patched_1.13.2.jar:git-Paper-486]
>         at com.destroystokyo.paper.util.PriorityQueuedExecutor.lambda$createPendingTask$1(PriorityQueuedExecutor.java:133) ~[patched_1.13.2.jar:git-Paper-486]
>         at com.destroystokyo.paper.util.PriorityQueuedExecutor$PendingTask.run(PriorityQueuedExecutor.java:273) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.requestChunk(PaperAsyncChunkProvider.java:197) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.loadOrGenerateChunk(PaperAsyncChunkProvider.java:154) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.getChunkAt(PaperAsyncChunkProvider.java:150) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:112) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.getChunkAt(PaperAsyncChunkProvider.java:136) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:389) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:385) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.World.getType(World.java:805) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getType(CraftBlock.java:181) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.citizensnpcs.nms.v1_13_R2.entity.MobEntityController.createEntity(MobEntityController.java:33) ~[?:?]
>         at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
>         at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:209) ~[?:?]
>         at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:143) ~[?:?]
>         at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
>         at net.citizensnpcs.Citizens$2.run(Citizens.java:306) ~[?:?]
>         at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-486]
>         at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-486]
>         at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-486]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by Blitheness** [comment]
The plugin still functions despite throwing these exceptions. The console is spammed whenever a player or minecart moves.

**Comment by oliverdunk** [comment]
Hi,

This is related to the regions feature in MCJukebox, which integrates with WorldGuard. The latest release should fix this, so please give that a try, and let me know how you get on 😄

**Comment by Blitheness** [comment]
Hi @oliverdunk, I am already using the latest release (2.6.0) while experiencing these problems.

**Comment by oliverdunk** [comment]
Hi again,

Could you try redownloading the jar for me? We updated it without making a new release.

**Comment by Blitheness** [comment]
@oliverdunk The problem is still ongoing after downloading the non-beta 2.6.0 jar file from the releases page

**Comment by oliverdunk** [comment]
@Blitheness Sorry for the time this is taking. Are you able to update WorldEdit and WorldGuard, or are they not compatible with the server version you're using?

**Comment by Blitheness** [comment]
Hi @oliverdunk, I've updated to your v2.6.1 release and the issue is ongoing.

Worldguard — http://ci.athion.net/job/FAWE-WorldGuard-1.13/58/
FAWE (FastAsyncWorldEdit) — http://ci.athion.net/job/FAWE-1.13/

>[20:20:13 ERROR]: Could not pass event PlayerTeleportEvent to MCJukebox v2.6.1
>java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
>        at net.mcjukebox.shared.wg7.RegionProvider.getApplicableRegions(RegionProvider.java:30) ~[?:?]
>        at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onMove(RegionListener.java:59) ~[?:?]
>        at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onTeleport(RegionListener.java:42) ~[?:?]
>        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor344.execute(Unknown Source) ~[?:?]
>        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-504]
>        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-504]
>        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-504]
>        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-504]
>        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:722) ~[patched_1.13.2.jar:git-Paper-504]
>        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:334) ~[patched_1.13.2.jar:git-Paper-504]
> ...


> [20:25:03 ERROR]: Could not pass event PlayerMoveEvent to MCJukebox v2.6.1
> java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
>         at net.mcjukebox.shared.wg7.RegionProvider.getApplicableRegions(RegionProvider.java:30) ~[?:?]
>         at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onMove(RegionListener.java:59) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor343.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-504]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-504]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-504]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-504]
>         at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1061) ~[patched_1.13.2.jar:git-Paper-504]
>         at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.2.jar:git-Paper-504]
>         at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.13.2.jar:git-Paper-504]
>         at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-504]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
>         at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-504]
>         at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-504]
>         at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-504]
>         at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-504]
>         at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-504]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

> > ver
>[20:21:25 INFO]: This server is running Paper version git-Paper-504 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
>[20:21:25 INFO]: Previous version: git-Paper-486 (MC: 1.13.2)
>[20:21:25 INFO]: Checking version, please wait...
>[20:21:26 INFO]: You are running the latest version

> > ver worldguard
> [20:21:58 INFO]: WorldGuard version 7.0.0-SNAPSHOT;0dc5781

The server uses Paper rather than Spigot (which hasn't caused the issue in this case as far as I'm aware)

The only thing I can think of being an issue is using FAWE (WorldEdit fork).

Using the latest dev builds of FAWE/worldguard/Paper.

**Comment by oliverdunk** [comment]
Hi,

I think the issue here is that FAWE are using code from an outdated version of WorldEdit. Unfortunately, there's little that we can do to help with that.

I hope you find a way to resolve this and apologise for my slow investigation.
